# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20161003_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='email',
            new_name='username',
        ),
    ]
