# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20161013_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
