# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160927_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('activity', models.CharField(max_length=256, null=True)),
                ('notes', models.CharField(max_length=10000, null=True)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users'),
        ),
    ]
