# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20160928_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='notes',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
