# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_users_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
