# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20161003_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='id',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='activity',
            field=models.CharField(default='act', max_length=256, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
