# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20161012_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
