# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20161013_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcheck',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailcheck',
            name='username',
        ),
    ]
